# =========================================================
# Application
# =========================================================

spring.application.name=email-automation
server.port=8080


# =========================================================
# Logging
# =========================================================

logging.level.root=INFO
logging.level.com.example.email_automation=DEBUG
logging.file.name=logs/email-automation.log


# =========================================================
# Email Export
# =========================================================

email.export.output-dir=processed_review
email.export.default-format=text


# =========================================================
# Gmail
# =========================================================

email.gmail.label=for_friend


# =========================================================
# ZIP Processing
# =========================================================

email.zip.export-dir=ready_to_send


# =========================================================
# Sent Archive
# =========================================================

email.sent.folder.name=send_archive