spring.application.name=email-automation
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/email_automation
spring.datasource.username=root
spring.datasource.password=Administrator

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.file.name=logs/email-automation.log
logging.level.com.example.email_automation=DEBUG

# Custom properties for email automation
email.export.output-dir=processed_review
email.export.default-format=text
email.gmail.label=for_friend
email.zip.export-dir=ready_to_send
email.sent.folder.name=send_archive